"""add current version

Revision ID: d8e273a5687f
Revises: 234fd4747a70
Create Date: 2024-06-04 15:53:24.057456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd8e273a5687f'
down_revision: Union[str, None] = '234fd4747a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elements', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('elements', sa.Column('selector', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('elements', sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('pages', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('project_versions', sa.Column('is_current_version', sa.Boolean(), nullable=False))
    op.add_column('scenarios', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('steps', sa.Column('command', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('steps', sa.Column('element_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('steps', sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'value')
    op.drop_column('steps', 'element_id')
    op.drop_column('steps', 'command')
    op.drop_column('scenarios', 'name')
    op.drop_column('project_versions', 'is_current_version')
    op.drop_column('pages', 'name')
    op.drop_column('elements', 'target')
    op.drop_column('elements', 'selector')
    op.drop_column('elements', 'name')
    # ### end Alembic commands ###
